name: CI/CD for React App

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build
      - name: Debugging output
        run: |
          echo "Host: ${{ secrets.SSH_HOST }}"
          echo "Username: ${{ secrets.SSH_USERNAME }}"
          echo "Key length: ${{ secrets.SSH_KEY }}}"

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd test
            git pull origin main
            ./deploy.sh

      # Uncomment the below section if you want to deploy to GitHub Pages
      # - name: Deploy to GitHub Pages
      #   uses: JamesIves/github-pages-deploy-action@4.1.0
      #   with:
      #     branch: gh-pages
      #     folder: build
